### ISSUE TITLE
SwaggerResponseExample is not working in version 2.2.0

### ISSUE THREAD

**Issue by ThaynaraSantos** [mattfrear/Swashbuckle.AspNetCore.Examples#16]
To work I had to downgrade to version 2.1.1

**Comment by mattfrear** [comment]
It's working for me. Can you try 2.2.1, which I just released a minute ago? If it's not working please post your code.

**Comment by ThaynaraSantos** [comment]
I tested and it's not working in version 2.2.1 too. I am using .net core 2.0 and bogus nuget, but even without bogus it's still not working in these versions (2.2.0/2.2.1).

My repository https://github.com/ThaynaraSantos/api-doc

**Comment by mattfrear** [comment]
Hmm I don't have .NET Core 2.0 installed on my dev box as it has issues with some of my existing .NET Core 1.1 solutions at work. I will try run your code under Core 1.1 and see if I can reproduce your issue.

**Comment by ThaynaraSantos** [comment]
Great, thanks!

**Comment by mattfrear** [comment]
What exactly is not working? I've moved your code to my Core 1.1 sample app:
```        
        [HttpGet]
        [Produces("application/json")]
        [SwaggerResponse((int)HttpStatusCode.OK, Type = typeof(IEnumerable<House>))]
        [SwaggerResponseExample((int)HttpStatusCode.OK, typeof(HouseGetExamples))]
        public IEnumerable<House> Get()```

```
    public class HouseGetExamples : IExamplesProvider
    {
        public object GetExamples()
        {
            HouseGetExample houseGetExample = new HouseGetExample();

            return new List<House>()
            {
                houseGetExample.GetExamples() as House,
                houseGetExample.GetExamples() as House
            };
        }
    }
```
```
    public class HouseGetExample : IExamplesProvider
    {
        public object GetExamples()
        {
            House house = new House {Address = "456 Bridge Street", Color = "Blue", Id = 1};
            return house;
        }
    }
```
![capture](https://user-images.githubusercontent.com/169179/30294022-908da7ae-9733-11e7-9869-5a693fc75ce8.JPG)

**Comment by ThaynaraSantos** [comment]
![docs](https://user-images.githubusercontent.com/7781785/30294765-9637d874-9714-11e7-84d7-75998c82e113.png)

Run the project and go to http://localhost:25111/docs 

The same response example, in version 2.1.1, is working.

**Comment by mattfrear** [comment]
I have reluctantly installed .NET 2.0 SDK on my dev machine just to try reproduce your issue.

I ran your repo - it works fine for me locally. Your repo was using 2.1.1 of my package. I updated your repo to use the latest version of my package - 2.2.1, and it still works fine.

I am testing this by going to /swagger:
![capture](https://user-images.githubusercontent.com/169179/30345799-6bff7c52-97fe-11e7-9620-d091742582f0.JPG)

I didn't know about the /docs page until you told me about it - what generates that? Is that part of Swashbuckle.AspNetCore? Ah, I see, it's a Redoc page. I've never heard of that. Anyway, that's working fine for me here too:

![capture2](https://user-images.githubusercontent.com/169179/30345911-eb58c09e-97fe-11e7-96f3-d11476894acb.JPG)

Hmm. I can't fix it for you if I can't reproduce it.

**Comment by ThaynaraSantos** [comment]
swagger.json generated in:

Version 2.1.1 (working)

![working](https://user-images.githubusercontent.com/7781785/30397006-d3f11afc-98a1-11e7-8b86-7708bd55c886.png)

Version 2.2.1 (not_working)

![not_working](https://user-images.githubusercontent.com/7781785/30397031-e3576bcc-98a1-11e7-9f6a-e25990198b66.png)

Maybe, the ReDoc script can't read the example in swagger.json after that change.

----------------------------------------------------------------------
For your knowledge. (https://github.com/Rebilly/ReDoc)

**Comment by mattfrear** [comment]
OK, so it IS working in Swagger-UI, which is where I test it, but not working in ReDoc.

I removed the application/json stuff by request as part of Issue #12.
There is a PR on my .NET Framework version of this project to optionally add it back in again https://github.com/mattfrear/Swashbuckle.Examples/pull/13

When I get a chance to do that I will port that PR to this project and then it should work again for ReDoc.

I have no idea why redoc needs application/json to work and that seems stupid, but I haven't been through their spec to make sense of it, as I only just heard of them.

**Comment by RomanGotsiy** [comment]
ReDoc author here.
Just to clarify, ReDoc behaves correctly here according to Swagger 2.0 spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject
Example object should be a map from `{mime type}` to example. So, technically, the output produced by 2.2.1 is invalid Swagger.

**Comment by mattfrear** [comment]
Thanks @RomanGotsiy for clarifying. I will revert the change so that my package produces valid Swagger as soon as I get a chance.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.2.2

**Comment by ThaynaraSantos** [comment]
Thank you! It's working fine now.

**Comment by mattfrear** [comment]
This seems to be fixed now with Swashbuckle 3.0
